export const STATUS_COLORS: Record<string, string> = {
  PENDING: 'bg-yellow-100 text-yellow-800 border-yellow-300',
  VERIFIED: 'bg-emerald-100 text-emerald-800 border-emerald-300',
  REJECTED: 'bg-red-100 text-red-800 border-red-300',
}

export const STATUS_LULUS_COLORS: Record<string, string> = {
  BELUM: 'bg-gray-100 text-gray-600 border-gray-300',
  LULUS: 'bg-emerald-100 text-emerald-800 border-emerald-300',
  TIDAK_LULUS: 'bg-red-100 text-red-800 border-red-300',
}

export const STATUS_DAFTAR_ULANG_COLORS: Record<string, string> = {
  BELUM: 'bg-gray-100 text-gray-600 border-gray-300',
  DAFTAR_ULANG: 'bg-blue-100 text-blue-800 border-blue-300',
  TIDAK_DAFTAR_ULANG: 'bg-orange-100 text-orange-800 border-orange-300',
}

// Kategori Kekurangan Verifikasi (tanpa nomor, bisa ditambah, tanpa duplikat)
export const DEFAULT_KEKURANGAN_OPTIONS = [
  ...new Set([
    'Tidak Ada Kendala',
    'Titik Koordinat tidak sesuai dengan Alamat di Kartu Keluarga',
    'Tidak Foto Rapor Semester 2',
    'Tidak Foto Rapor Semester 3',
    'Tidak Foto Rapor Semester 4',
    'Tidak Foto Rapor Semester 5',
    'Foto KK Buram tidak dapat dibaca',
    'Perubahan tempat dan tanggal tanda tangan pada surat pernyataan orang tua',
    'Foto Surat Keterangan Keabsahan Nilai Buram/ tidak dapat dibaca',
    'Tidak Ada Foto Surat Keterangan Kepala Sekolah (Keabsahan Nilai)',
    'Nilai Raport yang dientri tidak sesuai dengan foto nilai Per Semester',
    'Salah Input Nilai Raport Semester 1',
    'Salah Input Nilai Raport Semester 2',
    'Salah Input Nilai Raport Semester 3',
    'Salah Input Nilai Raport Semester 4',
    'Salah Input Nilai Raport Semester 5',
    'Tidak Ada Foto Rapor Sem 1, Sem 2, Sem 3, Sem 4',
    'Tidak Ada Foto Rapor Sem 1, Sem 2, Sem 3',
    'Tidak Ada Foto Rapor Sem 1, Sem 2',
    'Tidak Ada Foto Rapor Sem 1',
    'Tidak Ada Foto Rapor Sem 2',
    'Tidak Ada Foto Rapor Sem 3',
    'Tidak Ada Foto Rapor Sem 4',
    'Tidak Ada Foto Rapor Sem 5',
    'Tidak Ada Foto Rapor Samasekali',
    'Foto KK dan Surat Keterangan Buram',
    'Foto KK dan Rapor Buram',
    'Foto Surat Keterangan Kepala Sekolah dan Foto Rapor Buram',
    'Surat Pernyataan Orangtua/ Wali Tidak Dibubuhi Materai 10.000',
    'Titik Koordinat dan alamat di KK tidak sinkron',
    'Umur KK Baru 13 Hari',
    'Usia KK Masih Belum Setahun Silahkan Upload KK yang Diatas Satu tahun',
    'Umur KK Belum 1 Tahun',
    'Buram Foto Rapor Semester 2, 3, 4 dan 5',
    'Buram Foto Rapor Semester 3, 4 dan 5',
    'Buram Foto Rapor Semester 4 dan 5',
    'Surat pernyataan orang tua salah',
    'Foto raport yang di upload adalah foto raport asli dan bukan daftar kumpul',
    'Salah Upload bukti dokumen PIP',
    'Ditolak dinas',
    'KK tidak aktif segera aktifkan ke dukcapil serta surat keterangan tidak mampu',
    'KK tidak aktif segera aktifkan ke dukcapil supaya bisa mendaftar kembali',
    'Titik koordinat berbeda dan kartu keluarga tidak dapat di scan',
    'Kartu PKH sudah tidak aktif',
    'Titik koordinat salah dan KK tidak aktif',
    'Foto KK tidak dapat di scan',
    'Dokumen PKH yang diunggah salah dan surat pernyataan tidak sesuai form',
    'KK kurang dari 1 tahun dan nilai raport yang di input tidak sesuai dengan foto',
    'Nilai raport yang di input tidak sesuai dengan yang di upload',
    'KK tidak aktif, tidak ada kartu PKH, format pernyataan orang tua salah',
    'KK tidak aktif dan ket. Tempat dan tanggal surat pernyataan orang tua tidak sesuai',
    'KK tidak dapat dibaca dan hasil scan kartu KIP eror',
    'Dokumen KIP salah dan surat pernyataan orang tua kurang jelas',
    'KK tidak aktif dan titik koordinat salah',
    'KK kurang 1 tahun, dokumen KIP buram dan surat pernyataan orang tua tidak sesuai',
    'KK tidak aktif, foto raport tidak jelas dan tidak rapi',
    'Foto raport salah di upload',
    'KK blm 1 tahun, foto KIP buram dan tidak rapi',
    'Foto KK tidak dapat di baca',
    'Foto raport yang di upload pada semester 5 salah',
    'Alamat titik koordinat tidak sesuai dengan alamat di KK dan surat pernyataan',
    'Foto kartu KIP terpotong',
    'KK dan KIP tidak ditemukan serta tanda tangan tidak mengenai materai',
    'Nilai yang di input sem. 2 tidak sesuai dengan foto yang di upload',
    'Umur KK kurang dari 1 tahun dan foto raport tidak sesuai',
    'Nilai yang di input tidak sesuai dengan surat keabsahan nilai dari kasek',
    'KK tidak aktif',
    'Foto KK tdk dapat di scan',
    'Nilai raport sem. 1 yang di upload berbeda dengan surat keabsahan nilai raport',
    'Titik koordinat tidak sesuai, umur KK kurang dari 1 tahun, dokumen PKH salah',
    'KK tidak dapat di scan, titik koordinat tidak sesuai KK, kartu KIP tidak dapat di scan',
    'KK tidak dapat di baca dan kartu KIP eror saat di scan',
    'KK tidak dapat di baca dan titik koordinat tidak sesuai (titik di hutan)',
    'Foto raport semester 5 tidak lengkap dan KK tidak dapat discan',
    'KK buram dan salah upload foto raport',
    'KK tidak jelas, surat pernyataan salah',
    'KK dan kartu KIP tidak ditemukan',
    'Surat pernyataan keabsahan nilai raport salah',
    'Foto KK',
    'Kartu KIP tidak di upload',
    'Nilai sem. 4 dan 5 yang di input tidak sesuai dengan foto raport, umur KK kurang 1 tahun',
    'Titik koordinat tidak sesuai dengan KK, foto raport yang di upload tidak sesuai',
    'Foto raport tidak lengkap',
    'KK kurang 1 tahun dan surat keabsahan raport tidak sesuai',
    'Surat pernyataan dan kartu PKH tidak sesuai',
    'Umur KK kurang 1 tahun dan foto raport yang di upload salah',
    'KK kurang 1 tahun dan surat pernyataan tidak sesuai',
    'KK tidak aktif dan foto raport tidak lengkap',
    'Umur KK kurang 1 tahun dan nilai raport tidak sesuai dengan yang di input',
    'Foto raport semester 5 tidak lengkap',
    'Dokumen surat tugas tidak lengkap dan KK tidak aktif',
    'Foto raport terpotong',
    'Umur KK kurang 1 tahun',
    'Surat keabsahan yang di upload tidak sesuai',
  ])
]

export const SUB_JALUR_COLORS: Record<string, string> = {
  'Domisili': 'bg-gradient-to-r from-sky-100 to-blue-100 text-sky-800 border-sky-300',
  'Keluarga Tidak Mampu': 'bg-gradient-to-r from-orange-100 to-amber-100 text-orange-800 border-orange-300',
  'Afirmasi': 'bg-gradient-to-r from-orange-100 to-amber-100 text-orange-800 border-orange-300',
  'Jalur Afirmasi': 'bg-gradient-to-r from-orange-100 to-amber-100 text-orange-800 border-orange-300',
  'Penyandang Disabilitas': 'bg-gradient-to-r from-purple-100 to-violet-100 text-purple-800 border-purple-300',
  'Disabilitas': 'bg-gradient-to-r from-purple-100 to-violet-100 text-purple-800 border-purple-300',
  'Terdampak Bencana Alam': 'bg-gradient-to-r from-red-100 to-rose-100 text-red-800 border-red-300',
  'Anak Guru': 'bg-gradient-to-r from-pink-100 to-rose-100 text-pink-800 border-pink-300',
  'Mutasi Orangtua/Wali': 'bg-gradient-to-r from-cyan-100 to-teal-100 text-cyan-800 border-cyan-300',
  'Jalur Mutasi': 'bg-gradient-to-r from-cyan-100 to-teal-100 text-cyan-800 border-cyan-300',
  'Prestasi': 'bg-gradient-to-r from-emerald-100 to-green-100 text-emerald-800 border-emerald-300',
  'Prestasi Akademik': 'bg-gradient-to-r from-emerald-100 to-green-100 text-emerald-800 border-emerald-300',
  'Prestasi Nonakademik': 'bg-gradient-to-r from-teal-100 to-cyan-100 text-teal-800 border-teal-300',
  'Prestasi Non Akademik': 'bg-gradient-to-r from-teal-100 to-cyan-100 text-teal-800 border-teal-300',
  'Prestasi Non-Akademik': 'bg-gradient-to-r from-teal-100 to-cyan-100 text-teal-800 border-teal-300',
  'Mutasi': 'bg-gradient-to-r from-cyan-100 to-teal-100 text-cyan-800 border-cyan-300',
}
